# Retrieves information about the AWS identity currently used by Terraform.
# The AWS account ID is incorporated into the S3 bucket name to help ensure
# global uniqueness across environments and AWS accounts.
data "aws_caller_identity" "current" {}

# Creates the private S3 bucket used to receive incoming JSON event files.
resource "aws_s3_bucket" "ingestion" {
  # Combines the configured bucket prefix, deployment environment, and AWS
  # account ID to produce a predictable and globally unique bucket name.
  bucket = "${var.s3_bucket_prefix}-${var.environment}-${data.aws_caller_identity.current.account_id}"

  # Combines shared tags supplied by Terragrunt with resource-specific tags.
  tags = merge(
    var.common_tags,
    {
      Name        = "${var.s3_bucket_prefix}-${var.environment}"
      Environment = var.environment
    }
  )
}

# Blocks all forms of public access to the S3 ingestion bucket.
resource "aws_s3_bucket_public_access_block" "ingestion" {
  bucket = aws_s3_bucket.ingestion.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Configures object versioning for the S3 ingestion bucket.
resource "aws_s3_bucket_versioning" "ingestion" {
  bucket = aws_s3_bucket.ingestion.id

  versioning_configuration {
    status = var.s3_versioning_enabled ? "Enabled" : "Suspended"
  }
}

# Configures automatic expiration of ingested event objects.
resource "aws_s3_bucket_lifecycle_configuration" "ingestion" {
  bucket = aws_s3_bucket.ingestion.id

  rule {
    id     = "expire-ingested-events"
    status = "Enabled"

    # Applies this lifecycle rule only to objects uploaded for ingestion.
    filter {
      prefix = "incoming/"
    }

    # Removes current object versions after the configured retention period.
    expiration {
      days = var.s3_object_expiration_days
    }

    # Removes noncurrent object versions after the configured retention period
    # so versioning does not cause old event files to accumulate indefinitely.
    noncurrent_version_expiration {
      noncurrent_days = var.s3_object_expiration_days
    }
  }

  # Ensure versioning is configured before applying lifecycle behavior.
  depends_on = [
    aws_s3_bucket_versioning.ingestion,
  ]
}


# Enables Amazon EventBridge notifications for events generated by the
# S3 ingestion bucket. EventBridge rules can then route matching object
# creation events to downstream targets such as the SQS ingestion queue.
resource "aws_s3_bucket_notification" "ingestion" {
  bucket      = aws_s3_bucket.ingestion.id
  eventbridge = true
}


# Creates the DynamoDB table used to persist processed events.
resource "aws_dynamodb_table" "processed_events" {
  # Uses the caller-provided name for the DynamoDB table.
  name = var.dynamodb_table_name

  # Uses on-demand capacity so DynamoDB automatically handles request throughput.
  billing_mode = "PAY_PER_REQUEST"

  # Uses event_id as the partition key to uniquely identify processed events.
  hash_key = "event_id"

  # Defines the string attribute used as the table's partition key.
  attribute {
    name = "event_id"
    type = "S"
  }

  # Enables automatic cleanup of expired records using the configured
  # expiration timestamp attribute.
  ttl {
    attribute_name = var.dynamodb_ttl_attribute_name
    enabled        = true
  }

  # Combines shared tags supplied by Terragrunt with resource-specific tags.
  tags = merge(
    var.common_tags,
    {
      Name        = var.dynamodb_table_name
      Environment = var.environment
    }
  )
}
