# Creates an EventBridge rule on the default event bus that matches
# object-created events generated by the S3 ingestion bucket.
#
# The rule restricts processing to JSON files stored under the incoming/
# prefix so unrelated S3 objects do not enter the ingestion pipeline.
resource "aws_cloudwatch_event_rule" "ingestion" {
  # Include the deployment environment in the rule name so separate
  # environments can create independent copies of the pipeline.
  name = "${var.environment}-capture-ingestion-events"

  description = "Captures JSON event files created in the S3 ingestion bucket."

  # Match only S3 Object Created events originating from this pipeline's
  # ingestion bucket and whose object keys match incoming/*.json.
  event_pattern = jsonencode({
    source      = ["aws.s3"]
    detail-type = ["Object Created"]

    detail = {
      # Restrict the rule to the S3 bucket provided by the storage module.
      bucket = {
        name = [var.s3_bucket_name]
      }

      # Restrict processing to JSON event files under the incoming/ prefix.
      object = {
        key = [
          {
            wildcard = "incoming/*.json"
          }
        ]
      }
    }
  })
}

# Registers the SQS ingestion queue as the target of the EventBridge rule.
# Every S3 event matching the rule is delivered to this queue so ingestion
# remains asynchronous and decoupled from downstream Lambda processing.
resource "aws_cloudwatch_event_target" "ingestion_queue" {
  # Associate the target with the ingestion-specific EventBridge rule.
  rule = aws_cloudwatch_event_rule.ingestion.name

  # Provide a stable identifier for this target within the rule.
  target_id = "ingestion-sqs"

  # Deliver matching events to the SQS ingestion queue.
  arn = aws_sqs_queue.ingestion.arn
}

# Grants EventBridge permission to send messages to the SQS ingestion queue.
# SQS resource policies are required because the EventBridge service needs
# explicit authorization to invoke sqs:SendMessage against the queue.
resource "aws_sqs_queue_policy" "allow_eventbridge" {
  # Attach the resource policy to the processor module's ingestion queue.
  queue_url = aws_sqs_queue.ingestion.id

  policy = jsonencode({
    Version = "2012-10-17"

    Statement = [
      {
        Sid    = "AllowEventBridgeSendMessage"
        Effect = "Allow"

        # Allow the Amazon EventBridge service to perform the permitted action.
        Principal = {
          Service = "events.amazonaws.com"
        }

        # Grant only the permission EventBridge requires to deliver messages.
        Action = "sqs:SendMessage"

        # Restrict message delivery to this project's ingestion queue.
        Resource = aws_sqs_queue.ingestion.arn

        # Restrict the permission further so only this specific EventBridge
        # rule can use EventBridge to send messages to the ingestion queue.
        Condition = {
          ArnEquals = {
            "aws:SourceArn" = aws_cloudwatch_event_rule.ingestion.arn
          }
        }
      }
    ]
  })
}
